service: backend

frameworkVersion: "2 || 3"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  environment:
    COGNITO_USER_POOL: ${self:provider.stage}-user-pool
    COGNITO_USER_POOL_CLIENT: ${self:provider.stage}-user-pool-client

functions:
  home:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - USER_PASSWORD_AUTH
        GenerateSecret: false
