app: alpha
service: alpha

frameworkVersion: "2 || 3"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: "20201221"
  region: us-east-1

functions:
  home:
    handler: ./app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
