# Generated by Django 3.2.10 on 2021-12-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20211215_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='q_naire',
        ),
        migrations.AddField(
            model_name='research',
            name='q_naire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.qnaire'),
            preserve_default=False,
        ),
    ]
