# Generated by Django 3.2.10 on 2021-12-15 17:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_image_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='helper_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='part_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
