# Generated by Django 3.2.10 on 2021-12-20 11:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20211215_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='extra_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select(dropdown)'), ('checkbox', 'Checkbox'), ('radio', 'Radio button'), ('date', 'Date')], default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='helper_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
