# Generated by Django 3.2.10 on 2021-12-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211220_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('sub_section', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('q_naire', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('section', 'index')},
        ),
    ]
